[package]
name = "laughing-spork"
version = "0.1.0"
authors = ["Kristoffer Opsahl <post@kriops.no>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33"
rand = "0.8.1"